### ISSUE TITLE
20230409 15:49:44 ERROR    'STDERR "IOError: [Errno 2] No such file or directory: \'.\\\\\\\\b3\\\\\\\\extplugins\\\\\\\\conf\\\\\\\\disCOD.sql\'\\n"'

### ISSUE THREAD

**Issue by boultTech** [jyotirmay-exe/b3-plugin-disCOD#1]
```
20230409 15:49:44 ERROR    'STDERR "IOError: [Errno 2] No such file or directory: \'.\\\\\\\\b3\\\\\\\\extplugins\\\\\\\\conf\\\\\\\\disCOD.sql\'\\n"'
```

please help in resolving cod mw2 and cod4 server

**Comment by Zoro-6191** [comment]
copy paste [disCOD.sql](https://github.com/jyotirmay-exe/b3-plugin-disCOD/blob/master/conf/disCOD.sql) inside "b3\extplugins\conf\"

**Comment by boultTech** [comment]
> copy paste [disCOD.sql](https://github.com/jyotirmay-exe/b3-plugin-disCOD/blob/master/conf/disCOD.sql) inside "b3\extplugins\conf"

i tried this. it did not worked. 

also i want to keep discod.sql in b3 conf not extplugin conf. how to do that? please help

**Comment by jyotirmay-exe** [comment]
If you've tried pasting the SQL file in both `@b3/conf/` and `@b3/extplugins/conf/` and none of them worked, I would suggest checking the file name. It should be **disCOD.sql** (not `discod.sql` or something) since Linux file paths are case-sensitive.

As for keeping the SQL files in `@b3/conf/` instead of `@b3/extplugins/conf/`, there is a key `sqlpath` present in the main config. file [`plugin_discod.ini`](https://github.com/jyotirmay-exe/b3-plugin-disCOD/blob/master/conf/plugin_discod.ini) under `settings`. You can specify any location you want, provided that all the SQL files are also present there.

If you're still having such issues, a general workaround would be to use the latest updated version of the plugin, as all such issues were resolved before the latest release.

**Comment by boultTech** [comment]
ok. new version worked. thank you
